name: GitHub Actions CD to EC2
on:
  workflow_run:
    workflows: ["GitHub Actions CI"]
    types:
      - completed
  pull_request:
    branches:
      - main
env:
  CI: false
jobs:
  deploy:
    name: Run deployment script on EC2 instance 🚀
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Copy files to EC2
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          cd ${{ github.workspace }}/app1
          echo "$PRIVATE_KEY" > private_key.pem && chmod 600 private_key.pem
          scp -o StrictHostKeyChecking=no -i private_key.pem -r . ubuntu@${{ secrets.EC2_INSTANCE_IP }}.${{ secrets.AWS_REGION }}.compute.amazonaws.com:/home/ubuntu/app1
      - name: Build and run Docker image on EC2
        run: |
          sudo apt-get update
          sudo apt-get install apt-transport-https ca-certificates curl software-properties-common
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
          sudo apt-get update
          sudo apt-cache policy docker-c
          sudo apt-get install -y docker-ce
          sudo systemctl status docker
          docker build -t app1 .
          docker run -d -p 3000:3000 app1