name: GitHub Actions CD to EC2
on:
  workflow_run:
    workflows: ["GitHub Actions CI"]
    types:
      - completed
  push:
    branches:
      - main
env:
  CI: false
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  EC2_INSTANCE_IP: ${{ secrets.EC2_INSTANCE_IP }}
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
jobs:
  deploy:
    name: Run deployment script on EC2 instance 🚀
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Copy files to EC2
        run: |
          ls -la ${{ github.workspace }}
          cd ${{ github.workflow }}/app1
          scp -o StrictHostKeyChecking=no -i  -r . ubuntu@${{ secrets.EC2_INSTANCE_IP }}:/home/ubuntu/app1
      - name: Build and run Docker image on EC2
        run: |
          docker build -t app1 .
          docker run -d -p 3000:3000 app1