name: Continuous Integration Workflow
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push:
    branches:
      - testing
  pull_request:
    branches:
      - main
jobs:
  continuous_integration:
    name: Check code
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - run: echo "🍏 This job's status is ${{ job.status }}."
  unit_test:
    name: Run unit tests
    needs: continuous_integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install modules and run tests in app1
        run: |
          cd ${{ github.workspace }}/app1
          npm install
          npx jest --forceExit
  snyk:
   name: Scan vulnerabilities in app
   needs: continuous_integration
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@master
     - uses: actions/setup-node@v3
       with:
         node-version: '22.x'
         registry-url: 'https://registry.npmjs.org'
     - uses: snyk/actions/setup@master
     - name: Run snyk auth
       run: snyk auth ${{ secrets.SNYK_TOKEN }}
     - name: Run snyk code test
       run: snyk test --severity-threshold=high ${{ github.workspace }}/app2
     - name: Run snyk open source monitor
       run: snyk monitor --all-projects ${{ github.workspace }}/app2
     - name: Build a docker image
       run: |
          cd ${{ github.workspace }}/app1
          docker build -t junto-app1 .
     - name: Run snyk to check docker image for vulnerabilities
       continue-on-error: true
       uses: snyk/actions/docker@master
       with:
        image: junto-app1
        args: --file=Dockerfile
  trivy:
   name: Scan vulnerabilities in docker
   needs: continuous_integration
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@master
     - name: Build an image from dockerfile
       run: |
          cd ${{ github.workspace }}/app1
          docker build -t junto-app1 .
     - name: Run trivy vulnerability scanner
       uses: aquasecurity/trivy-action@0.20.0
       with:
         image-ref: junto-app1
         format: 'table'
         exit-code: '1'
         ignore-unfixed: true
         vuln-type: 'os,library'
         severity: 'CRITICAL'
