name: Deployment Workflow
on:
  workflow_run:
    workflows: ["Continuous Delivery Workflow"]
    types:
      - completed
  pull_request:
    branches:
      - main
  push: 
    branches:
      - junto-challenge
jobs:
  continuous_delivery:
    uses: ./.github/workflows/continous_delivery.yml
  testing:
    needs: continuous_delivery
    name: Run deployment script on EC2 instance 🚀
    runs-on: ubuntu-latest
    environment: testing
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Deploy to testing
        run: |
            aws deploy create-deployment \
            --application-name junto-app \
            --deployment-group-name AppDeploymentGroupName \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --github-location repository=${{ github.repository }},commitId=${{ github.sha }}
  production:
   needs: [continuous_delivery, testing]
   if: github.ref == 'refs/heads/main'
   name: Run deployment script on EC2 instance 🚀
   runs-on: ubuntu-latest
   environment: production
   steps:
     - uses: actions/checkout@v2
     - name: Configure AWS credentials
       uses: aws-actions/configure-aws-credentials@v1
       with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
     - name: Deploy to production
       run: |
        aws deploy create-deployment \
         --application-name junto-app \
         --deployment-group-name AppDeploymentGroupName \
         --deployment-config-name CodeDeployDefault.OneAtATime \
         --github-location repository=${{ github.repository }},commitId=${{ github.sha }}